export const rolesData = [
    // --- ฝ่ายชาวบ้าน (Villager Team) ---
    { id: 'v1', team: 'human', name: 'ชาวบ้าน', en: 'Villager', p: 1, desc: 'ไล่ล่าหาตัวหมาป่าให้เจอและกำจัดทิ้ง' },
    { id: 'v2', team: 'human', name: 'เทพพยากรณ์', en: 'Seer', p: 7, desc: 'ตรวจสอบผู้เล่นว่าเป็นหมาป่าหรือไม่' },
    { id: 'v3', team: 'human', name: 'จอมเวท', en: 'Spellcaster', p: 1, desc: 'เลือกผู้เล่นหนึ่งคนให้ห้ามพูดในวันถัดไป' },
    { id: 'v4', team: 'human', name: 'กามเทพ', en: 'Cupid', p: -3, desc: 'เลือกคู่รัก 2 คน หากคนใดตาย อีกคนจะตายตาม' },
    { id: 'v5', team: 'human', name: 'บอดี้การ์ด', en: 'Bodyguard', p: 3, desc: 'ปกป้องผู้เล่น 1 คน (ห้ามซ้ำคืนเดิม)' },
    { id: 'v6', team: 'human', name: 'ญาณทิพย์', en: 'Aura Seer', p: 3, desc: 'ตรวจสอบว่าผู้เล่นเป็นบทบาทพิเศษหรือไม่' },
    { id: 'v7', team: 'human', name: 'ขี้เมา', en: 'Drunk', p: 4, desc: 'รู้บทบาทจริงของตัวเองในคืนที่ 3' },
    { id: 'v8', team: 'human', name: 'เจ้าชาย', en: 'Prince', p: 3, desc: 'หากถูกโหวตประหาร จะไม่ตายและเผยบทบาท' },
    { id: 'v9', team: 'human', name: 'นักบวช', en: 'Priest', p: 3, desc: 'ปกป้องคนให้รอดจากการตายได้ 1 ครั้ง' },
    { id: 'v10', team: 'human', name: 'นักสืบเรื่องลี้ลับ', en: 'P.I.', p: 3, desc: 'ตรวจสอบเป้าหมายและข้างๆ ว่ามีหมาป่าไหม' },
    { id: 'v11', team: 'human', name: 'ตัวป่วน', en: 'Troublemaker', p: -3, desc: 'ทำให้โหวตกำจัดคนได้ 2 คนในวันถัดไป' },
    { id: 'v12', team: 'human', name: 'แม่มด', en: 'Witch', p: 4, desc: 'มียาชุบและยาฆ่า อย่างละ 1 ขวด' },
    { id: 'v13', team: 'human', name: 'แม่หมอ', en: 'Old Hag', p: 1, desc: 'สาปผู้เล่นให้โหวตไม่ได้ 1 วัน' },
    { id: 'v14', team: 'human', name: 'ศิษย์เทพพยากรณ์', en: 'Apprentice Seer', p: 4, desc: 'ถ้าเทพพยากรณ์ตาย คุณจะเป็นแทน' },
    { id: 'v15', team: 'human', name: 'นายกเทศมนตรี', en: 'Mayor', p: 2, desc: 'เสียงโหวตของคุณมีค่าเท่ากับ 2 เสียง' },
    { id: 'v16', team: 'human', name: 'นายพราน', en: 'Hunter', p: 3, desc: 'หากตาย สามารถเลือกยิงคนตายตามได้' },
    { id: 'v17', team: 'human', name: 'ผู้ป่วยติดเชื้อ', en: 'Disease', p: 3, desc: 'ถ้าถูกกิน หมาป่าจะฆ่าใครไม่ได้ในคืนถัดไป' },
    { id: 'v18', team: 'human', name: 'ผู้รักสันติ', en: 'Pacifist', p: -1, desc: 'ต้องโหวตให้ผู้เล่นรอดเสมอ' },
    { id: 'v19', team: 'human', name: 'พรายกระซิบ', en: 'Ghost', p: 2, desc: 'ตายคืนแรก สื่อสารได้วันละ 1 ตัวอักษร' },
    { id: 'v20', team: 'human', name: 'ภราดรแห่งเมสัน', en: 'Mason', p: 2, desc: 'รู้จักเพื่อนที่เป็น Mason ด้วยกัน' },
    { id: 'v21', team: 'human', name: 'ภูตจำแลง', en: 'Doppelganger', p: -2, desc: 'สวมรอยเป็นบทบาทของคนที่ตาย' },
    { id: 'v22', team: 'human', name: 'ลูกครึ่งหมาป่า', en: 'Lycan', p: -1, desc: 'ฝ่ายมนุษย์ แต่ Seer เห็นเป็นหมาป่า' },
    { id: 'v23', team: 'human', name: 'หนุ่มถึก', en: 'Tough Guy', p: 3, desc: 'ถ้าถูกฆ่า จะยังไม่ตายจนกว่าจะคืนถัดไป' },
    { id: 'v24', team: 'human', name: 'ไอ้ทึ่ม', en: 'Villager Idiot', p: 2, desc: 'ต้องโหวตให้ผู้เล่นถูกกำจัดเสมอ' },
    { id: 'e1', team: 'human', name: 'ผู้เผยตัวตน', en: 'Revealer', p: 4, desc: 'ชี้หมาป่าถ้าถูกฆ่า ถ้าผิดคุณตายแทน' },
    { id: 'e2', team: 'human', name: 'นักสะกดจิต', en: 'Mentalist', p: 6, desc: 'เช็คว่าผู้เล่น 2 คนอยู่ฝั่งเดียวกันไหม' },
    { id: 'e3', team: 'human', name: 'พรานหญิง', en: 'Huntress', p: 3, desc: 'ฆ่าคนได้ 1 ครั้งในเวลากลางคืน' },
    { id: 'e5', team: 'human', name: 'เทพผู้รู้แจ้ง', en: 'Mystic Seer', p: 9, desc: 'รู้บทบาทจริงของผู้เล่นที่ตรวจสอบทันที' },

    // --- ฝ่ายหมาป่า (Werewolf Team) ---
    { id: 'w1', team: 'wolf', name: 'มนุษย์หมาป่า', en: 'Werewolf', p: -6, desc: 'เลือกกำจัดผู้เล่น 1 คนในทุกคืน' },
    { id: 'w2', team: 'wolf', name: 'หมาป่าเดียวดาย', en: 'Lone Wolf', p: -5, desc: 'ชนะเมื่อเหลือรอดคนเดียว' },
    { id: 'w3', team: 'wolf', name: 'ลูกหมาป่า', en: 'Wolf Cub', p: -8, desc: 'ถ้าตาย หมาป่าจะฆ่าได้ 2 คน' },
    { id: 'w4', team: 'wolf', name: 'สมุนรับใช้', en: 'Minion', p: -6, desc: 'รู้ตัวหมาป่า แต่ไม่ได้ตื่นมาฆ่าด้วยกัน' },
    { id: 'w5', team: 'wolf', name: 'นางปีศาจ', en: 'Sorcerer', p: -3, desc: 'ค้นหาตัวเทพพยากรณ์ในคืน' },
    { id: 'w6', team: 'wolf', name: 'ผู้ต้องคำสาป', en: 'Cursed', p: -3, desc: 'ถ้าโดนกัด จะกลายเป็นหมาป่า' },
    { id: 'e6', team: 'wolf', name: 'หมาป่าจ่าฝูง', en: 'Alpha Wolf', p: -9, desc: 'เปลี่ยนเหยื่อเป็นหมาป่าตัวใหม่' },

    // --- ฝ่ายอิสระ/อื่นๆ (Solo/Special) ---
    { id: 'o1', team: 'other', name: 'อันธพาล', en: 'Hoodlum', p: 0, desc: 'เลือก 2 คน ถ้าทั้งคู่ตายและคุณรอด คุณชนะ' },
    { id: 'o2', team: 'other', name: 'ยาจก', en: 'Tanner', p: -2, desc: 'ชนะทันทีหากถูกโหวตประหาร' },
    { id: 'o3', team: 'other', name: 'แวมไพร์', en: 'Vampire', p: -7, desc: 'ฆ่าเหยื่อที่จะตายในวันถัดไป' },
    { id: 'o4', team: 'other', name: 'เจ้าลัทธิ', en: 'Cult Leader', p: 1, desc: 'ดึงคนเข้าลัทธิเพื่อชัยชนะ' },
    { id: 'e4', team: 'other', name: 'มือระเบิดพลีชีพ', en: 'Mad Bomber', p: -2, desc: 'ถ้าตาย คนซ้ายและขวาตายตาม' }
];
